import Images from  "@/public/images/product-image.png"

export const productsItem = [
    {
        id: 1,
        title: "Product name",
        price: 35.0,
        image: Images,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 2,
        title: "Product name",
        price: 35.0,
        image: Images,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 3,
        title: "Product name",
        price: 35.0,
        image: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 4,
        title: "Product name",
        price: 35.0,
        image: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 5,
        title: "Product name",
        price: 35.0,
        image: Images , 
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 6,
        title: "Product name",
        price: 35.0,
        image: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 7,
        title: "Product name",
        price: 35.0,
        image: Images , 
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 8,
        title: "Product name",
        price: 35.0,
        image: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 9,
        title: "Product name",
        price: 35.0,
        image: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 10,
        title: "Product name",
        price: 35.0,
        image: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 11,
        title: "Product name",
        price: 35.0,
        image: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 12,
        title: "Product name",
        price: 35.0,
        image: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
];
