import Images from  "@/public/images/product-image.png"

export const productsItem = [
    {
        id: 1,
        name: "Product name",
        price: 35.0,
        imgUrl: Images,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 2,
        name: "Product name",
        price: 35.0,
        imgUrl: Images,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 3,
        name: "Product name",
        price: 35.0,
        imgUrl: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 4,
        name: "Product name",
        price: 35.0,
        imgUrl: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 5,
        name: "Product name",
        price: 35.0,
        imgUrl: Images , 
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 6,
        name: "Product name",
        price: 35.0,
        imgUrl: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 7,
        name: "Product name",
        price: 35.0,
        imgUrl: Images , 
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 8,
        name: "Product name",
        price: 35.0,
        imgUrl: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 9,
        name: "Product name",
        price: 35.0,
        imgUrl: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 10,
        name: "Product name",
        price: 35.0,
        imgUrl: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 11,
        name: "Product name",
        price: 35.0,
        imgUrl: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
    {
        id: 12,
        name: "Product name",
        price: 35.0,
        imgUrl: Images ,
        isNewArrival: true,
        isFavorite: false,
    },
];
